name = "Boscia"
uuid = "630d6612-02b6-44cc-9b59-bf75311a0c58"
authors = ["Saurabh Srivastava"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
